name: Publish Itch.io
on: workflow_dispatch
jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
  
    - name: export game
      id: export
      uses: firebelley/godot-export@v5.2.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_mono_linux_x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_mono_export_templates.tpz
        relative_project_path: ./src/CardsPaperScissors.Game
        cache: true
        archive_output: false
        use_preset_export_path: true
        
    - name: Upload Builds
      uses: actions/upload-artifact@v2
      with:
        name: builds
        path: | 
          build/linux
          build/win
          